### ISSUE TITLE
ZOOT Update 

### ISSUE THREAD

**Issue by praneeth2699** [Fabb2303/ResurrectionRemix-M-Z00T#3]
Bro please release the new ZOOT update we are getting bored with the last update ! Thank you!

**Comment by Fabb2303** [comment]
kill boredom, Build it
https://github.com/ResurrectionRemix/platform_manifest
Have fun. So you don't get bored anymore. 💃

**Comment by praneeth2699** [comment]
Haha! I dont know how to build a ROM ! That is why I'm asking you! 😂 cause you're the maintainer
