### ISSUE TITLE
ZOOT Update 

### ISSUE THREAD

**Issue by praneeth2699** [Fabb2303/ResurrectionRemix-M-Z00T#4]
Hey fabio sir , i came here to notify you that in the last update of ZOOT i.e 12/05/2017 there is a boot lag( asus symbol is displayed for more seconds than normal and after 30-40 seconds of asus logo resurrection logo will appear) so please release an update which kills that bug

**Comment by Fabb2303** [comment]
Again :| 

Read Here
https://github.com/Fabb2303/ResurrectionRemix-Z00T/issues/3

**Comment by praneeth2699** [comment]
We are waiting sir its been 1 and half month still we are not getting a new update 😖😖😖 please fabio _/\_

**Comment by Fabb2303** [comment]
If you can't wait, build yourself

https://github.com/ResurrectionRemix/platform_manifest
👍 👍

**Comment by praneeth2699** [comment]
Then why you be the maintainer bro !😒😒

**Comment by Fabb2303** [comment]
The maintainers (and not just them) also have other commitments, such as work, school, university etc ...
Build a new update need a lot of time.
Try to be comprehensible.
As soon as I have some time, i will release a new update.
I have not abandoned the project. 
I'm sorry for waiting, but if you do not want to wait you can build it yourself, follow the link in post n°4. 👍

**Comment by praneeth2699** [comment]
Okay sorry for the disturbance that i caused to you! All the best to you personal work is 1st ! Take your own time we'll wait 🙂 ! I apology fabb  a big sorry !

**Comment by Fabb2303** [comment]
👍
